# Определение Deployment для приложения app1
apiVersion: apps/v1
kind: Deployment
metadata:
  # Имя Deployment
  name: deploy-app1
  labels:
    # Метка для приложения
    app: deploy-app1
spec:
  selector:
    matchLabels:
      # Метка для селектора
      app: app1
  template:
    metadata:
      labels:
        # Метка для шаблона
        app: app1
    spec:
      containers:
      - name: app1
        # Используемый образ nginx
        image: nginx:stable
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app1-volume
          # Точка монтирования для volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: app1-volume
        hostPath:
          # Путь на хосте для volume
          path: /vagrant/rsc/app1
---
# Определение Deployment для приложения app2
apiVersion: apps/v1
kind: Deployment
metadata:
  # Имя Deployment
  name: deploy-app2
  labels:
    # Метка для приложения
    app: deploy-app2
spec:
  replicas: 3
  selector:
    matchLabels:
      # Метка для селектора
      app: app2
  template:
    metadata:
      labels:
        # Метка для шаблона
        app: app2
    spec:
      containers:
      - name: app2
        # Используемый образ nginx
        image: nginx:stable
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app2-volume
          # Точка монтирования для volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: app2-volume
        hostPath:
          # Путь на хосте для volume
          path: /vagrant/rsc/app2
---
# Определение Deployment для приложения app3
apiVersion: apps/v1
kind: Deployment
metadata:
  # Имя Deployment
  name: deploy-app3
  labels:
    # Метка для приложения
    app: deploy-app3
spec:
  selector:
    matchLabels:
      # Метка для селектора
      app: app3
  template:
    metadata:
      labels:
        # Метка для шаблона
        app: app3
    spec:
      containers:
      - name: app3
        # Используемый образ nginx
        image: nginx:stable
        ports:
        - containerPort: 80
        volumeMounts:
        - name: app3-volume
          # Точка монтирования для volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: app3-volume
        hostPath:
          # Путь на хосте для volume
          path: /vagrant/rsc/app3
---
# Определение Service для приложения app1
apiVersion: v1
kind: Service
metadata:
  # Имя Service
  name: svc-app1
spec:
  selector:
    # Селектор для Service
    app: app1
  ports:
    - protocol: TCP
      # Порт Service
      port: 8080
      # Целевой порт контейнера
      targetPort: 80
---
# Определение Service для приложения app2
apiVersion: v1
kind: Service
metadata:
  # Имя Service
  name: svc-app2
spec:
  selector:
    # Селектор для Service
    app: app2
  ports:
    - protocol: TCP
      # Порт Service
      port: 8080
      # Целевой порт контейнера
      targetPort: 80
---
# Определение Service для приложения app3
apiVersion: v1
kind: Service
metadata:
  # Имя Service
  name: svc-app3
spec:
  selector:
    # Селектор для Service
    app: app3
  ports:
    - protocol: TCP
      # Порт Service
      port: 8080
      # Целевой порт контейнера
      targetPort: 80
---
# Определение Ingress для приложений
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  # Имя Ingress
  name: ingress-apps
spec:
  rules:
  - host: app1.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            # Имя Service для app1
            name: svc-app1
            port:
              number: 8080
  - host: app2.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            # Имя Service для app2
            name: svc-app2
            port:
              number: 8080
  - host: app3.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            # Имя Service для app3
            name: svc-app3
            port:
              number: 8080
  - host:
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            # Имя Service для app3
            name: svc-app3
            port:
              number: 8080
