Vagrant.configure("2") do |config|
	# Определение виртуальной машины "sberS"
	config.vm.define "sberS" do |server|
	  # Установка базового образа для виртуальной машины
	  server.vm.box = "ubuntu/bionic64"
	  # Установка имени хоста для виртуальной машины
	  server.vm.hostname = "sberS"
	  # Настройка приватной сети с IP-адресом 192.168.42.110
	  server.vm.network "private_network", ip: "192.168.42.110"
	  # Настройка провайдера VirtualBox для виртуальной машины
	  server.vm.provider "virtualbox" do |vb|
		# Установка объема памяти в 2048 МБ
		vb.memory = 2048
		# Установка количества процессоров в 2
		vb.cpus = 2
	  end
	  # Настройка сценария инициализации для виртуальной машины
	  server.vm.provision "shell", path: "scripts/server.sh"
	end
  
	# Определение виртуальной машины "sberSW"
	config.vm.define "sberSW" do |worker|
	  worker.vm.box = "ubuntu/bionic64"
	  worker.vm.hostname = "sberSW"
	  worker.vm.network "private_network", ip: "192.168.42.111"
	  worker.vm.provider "virtualbox" do |vb|
		vb.memory = 2048
		vb.cpus = 2
	  end
	  worker.vm.provision "shell", path: "scripts/worker.sh"
	end
  end
  